### ISSUE TITLE
Plugin missing New albums>New albums and Top albums>Top Albums

### ISSUE THREAD

**Issue by sonofdibnah** [L2501/plugin.audio.m3sr2019#1]
I posted about this in Bugatsinho's repo but this requests belongs here really. In the original addon it was possible to view all new albums irrespective of genre by selecting New Albums and then the New Albums option that appeared at the top of the list of available genres. Top Albums behaved similarly. By using these options it was possible to browse and discover new music without a preconceived notion about genre. For myself this was very useful and led me to enjoy music I would not have come across in my preferred genre of Folk Rock.

Would it be possible please to add these options into the Reloaded addon?

**Comment by L2501** [comment]
I think you can use "world" category that includes everything.

**Comment by sonofdibnah** [comment]
I've checked and you are correct that the "World" sections do show everything. That's good enough for me.
