### ISSUE TITLE
Kodi 18 crashes when trying to play an album

### ISSUE THREAD

**Issue by sonofdibnah** [L2501/plugin.audio.m3sr2019#2]
I use this addon regularly. Yesterday I noted that kodi crashes and ultimately restarts when I try to play any album. I've dug around a little and can say that it is only on kodi 18 (Coreelec on amlogic and on my android phone). The addon continues to work on kodi 17.6 on my old phone.

I'm not clever enough to do anything but speculate as to the cause but I did notice that Kodi Six has recently been updated in kodi 18.

This is a great addon and I do hope that this issue can be fixed. Thanks in anticipation

**Comment by sonofdibnah** [comment]
Please ignore what i said about Kodi Six. I tried rollong back to version 0.1.1 and still had the kodi crash.

**Comment by sonofdibnah** [comment]
Sorry didn't mean to close the issue. I'm new to this

**Comment by jajalobrit** [comment]
Same thing happens here with kodi 18 on a raspberry.

**Comment by L2501** [comment]
Looks like their SSL certificate expired, it's a known kodi bug that causes crash when http audio stream playback fails. Disabled cert check in new release https://github.com/L2501/plugin.audio.m3sr2019/releases/tag/v6

**Comment by sonofdibnah** [comment]
Thank you L2501 for the quick fix. Much appreciated.
