### ISSUE TITLE
Favourites folder request in Reloaded?

### ISSUE THREAD

**Issue by DROIDshield** [L2501/plugin.audio.m3sr2019#4]
Is there any chance of adding a favourites folder in this addon. Your previous mp3 addon had one, this made it easy to add an artist or album to it so that could be recalled without going back to the search item again?

**Comment by L2501** [comment]
there is no reason for every plugin to re-implement basic kodi features.

**Comment by DROIDshield** [comment]
IMHO, I think it's a very useful feature. When you come across that track or album or artist you feel hits the spot, it nice to be able to recall at a drop from a favourites list... but I bow to your dev skills and go with your thoughts. 

Cheers for your work, it's well appreciated.
